# Generated by Django 4.0.3 on 2022-04-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helping_hands', '0002_remove_employee_transaction_employee_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
