# Generated by Django 4.0.3 on 2022-04-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helping_hands', '0003_rename_customer_id_job_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
