# Generated by Django 4.0.3 on 2022-04-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helping_hands', '0004_rename_employee_id_offer_employee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='job_id',
            new_name='job',
        ),
    ]
