# Generated by Django 4.0.3 on 2022-04-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helping_hands', '0005_rename_job_id_offer_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='lat',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='lng',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='lat',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='lng',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
